name: CI
on:
  push:
    branches-ignore:
      - "master"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  - name: Create comment
   uses: thollander/actions-comment-pull-request@v2
   with:
    message: |
      Hello world ! :wave:
    GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
